[36m[2019-10-21 01:23:52 DEBUG] [cli:70][39m ###############################################################################
[36m[2019-10-21 01:23:52 DEBUG] [cli:71][39m Running command 'run'
[36m[2019-10-21 01:23:52 DEBUG] [cli:75][39m Using settings file '/home/guicpupio/.chaostoolkit/settings.yaml'
[36m[2019-10-21 01:23:52 DEBUG] [settings:24][39m The Chaos Toolkit settings file could not be found at '/home/guicpupio/.chaostoolkit/settings.yaml'.
[36m[2019-10-21 01:23:52 DEBUG] [__init__:355][39m No controls to apply on 'loader'
[36m[2019-10-21 01:23:52 DEBUG] [__init__:355][39m No controls to apply on 'loader'
[36m[2019-10-21 01:23:52 DEBUG] [caching:25][39m Building activity cache...
[36m[2019-10-21 01:23:52 DEBUG] [caching:35][39m Cached 3 activities
[32m[2019-10-21 01:23:52 INFO] [experiment:54][39m Validating the experiment's syntax
[36m[2019-10-21 01:23:52 DEBUG] [configuration:36][39m Loading configuration...
[36m[2019-10-21 01:23:52 DEBUG] [secret:74][39m Loading secrets...
[36m[2019-10-21 01:23:52 DEBUG] [secret:89][39m Secrets loaded
[32m[2019-10-21 01:23:52 INFO] [experiment:100][39m Experiment looks valid
[36m[2019-10-21 01:23:52 DEBUG] [caching:42][39m Clearing activities cache
[36m[2019-10-21 01:23:52 DEBUG] [caching:25][39m Building activity cache...
[36m[2019-10-21 01:23:52 DEBUG] [caching:35][39m Cached 3 activities
[32m[2019-10-21 01:23:52 INFO] [experiment:179][39m Running experiment: Derrubando os micro servico provedor, a aplicacao se mantem em pe
[36m[2019-10-21 01:23:52 DEBUG] [configuration:36][39m Loading configuration...
[36m[2019-10-21 01:23:52 DEBUG] [secret:74][39m Loading secrets...
[36m[2019-10-21 01:23:52 DEBUG] [secret:89][39m Secrets loaded
[36m[2019-10-21 01:23:52 DEBUG] [__init__:39][39m Initializing controls
[36m[2019-10-21 01:23:52 DEBUG] [__init__:355][39m No controls to apply on 'experiment'
[32m[2019-10-21 01:23:52 INFO] [hypothesis:184][39m Steady state hypothesis: Verificando Status do Servico Consumidor
[36m[2019-10-21 01:23:52 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[36m[2019-10-21 01:23:52 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2019-10-21 01:23:52 INFO] [activity:158][39m Probe: Comunicando com Servico Consumidor
[36m[2019-10-21 01:23:52 DEBUG] [process:53][39m Running: /bin/sh get-info-consumidor.sh
[36m[2019-10-21 01:23:53 DEBUG] [activity:176][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[32m[2019-10-21 01:23:53 INFO] [activity:195][39m Pausing after activity for 1s...
[36m[2019-10-21 01:23:54 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2019-10-21 01:23:54 DEBUG] [hypothesis:212][39m allowed tolerance is [0]
[36m[2019-10-21 01:23:54 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2019-10-21 01:23:54 INFO] [activity:158][39m Probe: Verifica status da resposta do consumidor
[36m[2019-10-21 01:23:54 DEBUG] [process:53][39m Running: /bin/egrep '200' status_consumidor.log
[36m[2019-10-21 01:23:54 DEBUG] [__init__:115][39m Data encoding detected as 'ascii' with a confidence of 1.0
[36m[2019-10-21 01:23:54 DEBUG] [activity:176][39m   => succeeded with '{'status': 0, 'stdout': '200\n', 'stderr': ''}'
[36m[2019-10-21 01:23:54 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2019-10-21 01:23:54 DEBUG] [hypothesis:212][39m allowed tolerance is [0]
[32m[2019-10-21 01:23:54 INFO] [hypothesis:222][39m Steady state hypothesis is met!
[36m[2019-10-21 01:23:54 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[36m[2019-10-21 01:23:54 DEBUG] [__init__:355][39m No controls to apply on 'method'
[36m[2019-10-21 01:23:54 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2019-10-21 01:23:54 INFO] [activity:158][39m Action: Mata o Servico Consumidor
[36m[2019-10-21 01:23:54 DEBUG] [process:53][39m Running: /usr/bin/kubectl scale deployment --replicas=0 my-provider-app 
[36m[2019-10-21 01:23:54 DEBUG] [__init__:115][39m Data encoding detected as 'ascii' with a confidence of 1.0
[36m[2019-10-21 01:23:54 DEBUG] [activity:176][39m   => succeeded with '{'status': 0, 'stdout': 'deployment.apps/my-provider-app scaled\n', 'stderr': ''}'
[32m[2019-10-21 01:23:54 INFO] [activity:195][39m Pausing after activity for 10s...
[36m[2019-10-21 01:24:04 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2019-10-21 01:24:04 DEBUG] [__init__:355][39m No controls to apply on 'method'
[32m[2019-10-21 01:24:04 INFO] [hypothesis:184][39m Steady state hypothesis: Verificando Status do Servico Consumidor
[36m[2019-10-21 01:24:04 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[36m[2019-10-21 01:24:04 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2019-10-21 01:24:04 INFO] [activity:158][39m Probe: Comunicando com Servico Consumidor
[36m[2019-10-21 01:24:04 DEBUG] [process:53][39m Running: /bin/sh get-info-consumidor.sh
[36m[2019-10-21 01:24:04 DEBUG] [activity:176][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[32m[2019-10-21 01:24:04 INFO] [activity:195][39m Pausing after activity for 1s...
[36m[2019-10-21 01:24:05 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2019-10-21 01:24:05 DEBUG] [hypothesis:212][39m allowed tolerance is [0]
[36m[2019-10-21 01:24:05 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2019-10-21 01:24:05 INFO] [activity:158][39m Probe: Verifica status da resposta do consumidor
[36m[2019-10-21 01:24:05 DEBUG] [process:53][39m Running: /bin/egrep '200' status_consumidor.log
[36m[2019-10-21 01:24:05 DEBUG] [__init__:115][39m Data encoding detected as 'ascii' with a confidence of 1.0
[36m[2019-10-21 01:24:05 DEBUG] [activity:176][39m   => succeeded with '{'status': 0, 'stdout': '200\n', 'stderr': ''}'
[36m[2019-10-21 01:24:05 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2019-10-21 01:24:05 DEBUG] [hypothesis:212][39m allowed tolerance is [0]
[32m[2019-10-21 01:24:05 INFO] [hypothesis:222][39m Steady state hypothesis is met!
[36m[2019-10-21 01:24:05 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[32m[2019-10-21 01:24:05 INFO] [experiment:320][39m Let's rollback...
[36m[2019-10-21 01:24:05 DEBUG] [__init__:355][39m No controls to apply on 'rollback'
[32m[2019-10-21 01:24:05 INFO] [rollback:28][39m Rollback: Restaura o Servico Consumidor 
[36m[2019-10-21 01:24:05 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2019-10-21 01:24:05 INFO] [activity:158][39m Action: Restaura o Servico Consumidor 
[36m[2019-10-21 01:24:05 DEBUG] [process:53][39m Running: /usr/bin/kubectl scale deployment --replicas=2 my-provider-app
[36m[2019-10-21 01:24:05 DEBUG] [__init__:115][39m Data encoding detected as 'ascii' with a confidence of 1.0
[36m[2019-10-21 01:24:05 DEBUG] [activity:176][39m   => succeeded with '{'status': 0, 'stdout': 'deployment.apps/my-provider-app scaled\n', 'stderr': ''}'
[36m[2019-10-21 01:24:05 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2019-10-21 01:24:05 DEBUG] [__init__:355][39m No controls to apply on 'rollback'
[32m[2019-10-21 01:24:05 INFO] [experiment:270][39m Experiment ended with status: completed
[36m[2019-10-21 01:24:05 DEBUG] [__init__:355][39m No controls to apply on 'experiment'
[36m[2019-10-21 01:24:05 DEBUG] [__init__:72][39m Cleaning up controls
[36m[2019-10-21 01:24:05 DEBUG] [caching:42][39m Clearing activities cache
[36m[2019-10-21 01:49:28 DEBUG] [cli:70][39m ###############################################################################
[36m[2019-10-21 01:49:28 DEBUG] [cli:71][39m Running command 'run'
[36m[2019-10-21 01:49:28 DEBUG] [cli:75][39m Using settings file '/home/guicpupio/.chaostoolkit/settings.yaml'
[36m[2019-10-21 01:49:28 DEBUG] [settings:24][39m The Chaos Toolkit settings file could not be found at '/home/guicpupio/.chaostoolkit/settings.yaml'.
[36m[2019-10-21 01:49:28 DEBUG] [__init__:355][39m No controls to apply on 'loader'
[36m[2019-10-21 01:49:28 DEBUG] [__init__:355][39m No controls to apply on 'loader'
[36m[2019-10-21 01:49:28 DEBUG] [caching:25][39m Building activity cache...
[36m[2019-10-21 01:49:28 DEBUG] [caching:35][39m Cached 3 activities
[32m[2019-10-21 01:49:28 INFO] [experiment:54][39m Validating the experiment's syntax
[36m[2019-10-21 01:49:28 DEBUG] [configuration:36][39m Loading configuration...
[36m[2019-10-21 01:49:28 DEBUG] [secret:74][39m Loading secrets...
[36m[2019-10-21 01:49:28 DEBUG] [secret:89][39m Secrets loaded
[32m[2019-10-21 01:49:28 INFO] [experiment:100][39m Experiment looks valid
[36m[2019-10-21 01:49:28 DEBUG] [caching:42][39m Clearing activities cache
[36m[2019-10-21 01:49:28 DEBUG] [caching:25][39m Building activity cache...
[36m[2019-10-21 01:49:28 DEBUG] [caching:35][39m Cached 3 activities
[32m[2019-10-21 01:49:28 INFO] [experiment:179][39m Running experiment: Derrubando os micro servico provedor, a aplicacao se mantem em pe
[36m[2019-10-21 01:49:28 DEBUG] [configuration:36][39m Loading configuration...
[36m[2019-10-21 01:49:28 DEBUG] [secret:74][39m Loading secrets...
[36m[2019-10-21 01:49:28 DEBUG] [secret:89][39m Secrets loaded
[36m[2019-10-21 01:49:28 DEBUG] [__init__:39][39m Initializing controls
[36m[2019-10-21 01:49:28 DEBUG] [__init__:355][39m No controls to apply on 'experiment'
[32m[2019-10-21 01:49:28 INFO] [hypothesis:184][39m Steady state hypothesis: Verificando Status do Servico Consumidor
[36m[2019-10-21 01:49:28 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[36m[2019-10-21 01:49:28 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2019-10-21 01:49:28 INFO] [activity:158][39m Probe: Comunicando com Servico Consumidor
[36m[2019-10-21 01:49:28 DEBUG] [process:53][39m Running: /bin/sh get-info-consumidor.sh
[36m[2019-10-21 01:49:29 DEBUG] [activity:176][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[32m[2019-10-21 01:49:29 INFO] [activity:195][39m Pausing after activity for 1s...
[36m[2019-10-21 01:49:30 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2019-10-21 01:49:30 DEBUG] [hypothesis:212][39m allowed tolerance is [0]
[36m[2019-10-21 01:49:30 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2019-10-21 01:49:30 INFO] [activity:158][39m Probe: Verifica status da resposta do consumidor
[36m[2019-10-21 01:49:30 DEBUG] [process:53][39m Running: /bin/egrep '200' status_consumidor.log
[36m[2019-10-21 01:49:30 DEBUG] [__init__:115][39m Data encoding detected as 'ascii' with a confidence of 1.0
[36m[2019-10-21 01:49:30 DEBUG] [activity:176][39m   => succeeded with '{'status': 0, 'stdout': '200\n', 'stderr': ''}'
[36m[2019-10-21 01:49:30 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2019-10-21 01:49:30 DEBUG] [hypothesis:212][39m allowed tolerance is [0]
[32m[2019-10-21 01:49:30 INFO] [hypothesis:222][39m Steady state hypothesis is met!
[36m[2019-10-21 01:49:30 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[36m[2019-10-21 01:49:30 DEBUG] [__init__:355][39m No controls to apply on 'method'
[36m[2019-10-21 01:49:30 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2019-10-21 01:49:30 INFO] [activity:158][39m Action: Mata o Servico Provedor
[36m[2019-10-21 01:49:30 DEBUG] [process:53][39m Running: /usr/bin/kubectl scale deployment --replicas=0 my-provider-app 
[36m[2019-10-21 01:49:30 DEBUG] [__init__:115][39m Data encoding detected as 'ascii' with a confidence of 1.0
[36m[2019-10-21 01:49:30 DEBUG] [activity:176][39m   => succeeded with '{'status': 0, 'stdout': 'deployment.apps/my-provider-app scaled\n', 'stderr': ''}'
[32m[2019-10-21 01:49:30 INFO] [activity:195][39m Pausing after activity for 20s...
[36m[2019-10-21 01:49:50 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2019-10-21 01:49:50 DEBUG] [__init__:355][39m No controls to apply on 'method'
[32m[2019-10-21 01:49:50 INFO] [hypothesis:184][39m Steady state hypothesis: Verificando Status do Servico Consumidor
[36m[2019-10-21 01:49:50 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[36m[2019-10-21 01:49:50 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2019-10-21 01:49:50 INFO] [activity:158][39m Probe: Comunicando com Servico Consumidor
[36m[2019-10-21 01:49:50 DEBUG] [process:53][39m Running: /bin/sh get-info-consumidor.sh
[36m[2019-10-21 01:50:00 DEBUG] [activity:176][39m   => succeeded with '{'status': 0, 'stdout': '', 'stderr': ''}'
[32m[2019-10-21 01:50:00 INFO] [activity:195][39m Pausing after activity for 1s...
[36m[2019-10-21 01:50:01 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2019-10-21 01:50:01 DEBUG] [hypothesis:212][39m allowed tolerance is [0]
[36m[2019-10-21 01:50:01 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2019-10-21 01:50:01 INFO] [activity:158][39m Probe: Verifica status da resposta do consumidor
[36m[2019-10-21 01:50:01 DEBUG] [process:53][39m Running: /bin/egrep '200' status_consumidor.log
[36m[2019-10-21 01:50:01 DEBUG] [activity:176][39m   => succeeded with '{'status': 1, 'stdout': '', 'stderr': ''}'
[36m[2019-10-21 01:50:01 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2019-10-21 01:50:01 DEBUG] [hypothesis:212][39m allowed tolerance is [0]
[36m[2019-10-21 01:50:01 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[2019-10-21 01:50:01 CRITICAL] [experiment:241] Steady state probe 'Verifica status da resposta do consumidor' is not in the given tolerance so failing this experiment
[32m[2019-10-21 01:50:01 INFO] [experiment:320][39m Let's rollback...
[36m[2019-10-21 01:50:01 DEBUG] [__init__:355][39m No controls to apply on 'rollback'
[32m[2019-10-21 01:50:01 INFO] [rollback:28][39m Rollback: Restaura o Servico Consumidor 
[36m[2019-10-21 01:50:01 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2019-10-21 01:50:01 INFO] [activity:158][39m Action: Restaura o Servico Consumidor 
[36m[2019-10-21 01:50:01 DEBUG] [process:53][39m Running: /usr/bin/kubectl scale deployment --replicas=2 my-provider-app
[36m[2019-10-21 01:50:01 DEBUG] [__init__:115][39m Data encoding detected as 'ascii' with a confidence of 1.0
[36m[2019-10-21 01:50:01 DEBUG] [activity:176][39m   => succeeded with '{'status': 0, 'stdout': 'deployment.apps/my-provider-app scaled\n', 'stderr': ''}'
[36m[2019-10-21 01:50:01 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2019-10-21 01:50:01 DEBUG] [__init__:355][39m No controls to apply on 'rollback'
[32m[2019-10-21 01:50:01 INFO] [experiment:270][39m Experiment ended with status: deviated
[32m[2019-10-21 01:50:01 INFO] [experiment:274][39m The steady-state has deviated, a weakness may have been discovered
[36m[2019-10-21 01:50:01 DEBUG] [__init__:355][39m No controls to apply on 'experiment'
[36m[2019-10-21 01:50:01 DEBUG] [__init__:72][39m Cleaning up controls
[36m[2019-10-21 01:50:01 DEBUG] [caching:42][39m Clearing activities cache
